### ISSUE TITLE
Scrolling using trackpad on macos does not work

### ISSUE THREAD

**Issue by ashbrowning** [retyui/react-quick-pinch-zoom#10]
When using two fingers to scroll on a macos trackpad, nothing happens whereas I would expect a normal scroll experience. Pinching-to-zoom works fine, which is based off the same WheelEvent (just that the event.ctrl flag is set to true).

**Comment by retyui** [comment]
Please use [shouldInterceptWheel](https://github.com/retyui/react-quick-pinch-zoom/blob/master/docs/api/README.md#shouldinterceptwheel-wheelevent--boolean) to change this behavior:

```js
const shouldInterceptWheel = () => false;

return <QuickPinchZoom 
    shouldInterceptWheel={shouldInterceptWheel}
    onUpdate={onUpdate}>
      <img ref={imgRef} src={IMG_URL} />
</QuickPinchZoom>;
```

**Comment by ashbrowning** [comment]
This will mean that the scrolling gestures on the trackpad, as well as the scrolling the wheel on a mouse, will result in zooming in/out of the content. 

Surely there's a case for supporting both scrolling and zooming of the content via the wheelEvent?

**Comment by ashbrowning** [comment]
@retyui - what are your thoughts on the above?

**Comment by retyui** [comment]
I hardly understand the problem that you want report

- CMD + scrolling (zoom image)
- Pinch and zoom gesture (zoom image)
