### ISSUE TITLE
Calling alignCenter for the second time

### ISSUE THREAD

**Issue by motro** [retyui/react-quick-pinch-zoom#2]
Hi there,

First of all, thanks for the great package!

I'm trying the following:

1. Calling alignCenter with my X and Y where I just clicked and a scale of 2 - works great.
2. After another click, calling alignCenter again with different X and Y values but the same scale which results in a weird positioning of the center.

What would be the correct way to align the center again to a different point using the same scale?

**Comment by retyui** [comment]
@motro 
Can you create a demo on [codesandbox](https://codesandbox.io/s/new) to see your problem

**Comment by motro** [comment]
@retyui see a demo here: https://codesandbox.io/embed/ryfcx
what I'm trying to do is to zoom to the point where I clicked, looks like something is lost in translation between the different coordinates systems (SVG/DOM).

**Comment by motro** [comment]
I had solved it :) all I needed was to set the viewBox of the SVG to the viewport size instead of the image size.
