### ISSUE TITLE
Focus support for children

### ISSUE THREAD

**Issue by j1mie** [retyui/react-quick-pinch-zoom#25]
Hi there, I'm wondering if it's possible to focus child components, using this library?

Currently, I'm unable to focus by clicking any element within `QuickPinchZoom`.

**Comment by retyui** [comment]
Could you please create a demo to show this issue?

**Comment by j1mie** [comment]
Sure thing: https://codesandbox.io/s/red-sound-pydro?file=/src/styles.css

**Comment by retyui** [comment]
This happens when called a next line:

https://github.com/retyui/react-quick-pinch-zoom/blob/84be39f5f90302687a6b4343debb040dbc1dd90f/src/PinchZoom/component.tsx#L862


And you can overwrite this behavior As a workaround https://codesandbox.io/s/naughty-kepler-qxbj4


```js
import QuickPinchZoom from "react-quick-pinch-zoom";


class MyQuickPinchZoom extends  QuickPinchZoom {
   simulate(fn) {
    return mouseEvent => {
      const { pageX, pageY, type } = mouseEvent;
      const isEnd = type === "mouseup";
      const isStart = type === "mousedown";

      if (isStart) {
       // FIXME: To have able focus elemnts
       // mouseEvent.preventDefault();

        this._listenMouseMove = true;
      }

      if (this._listenMouseMove) {
        mouseEvent.touches = isEnd ? [] : [{ pageX, pageY }];

        fn(mouseEvent);
      }

      if (isEnd) {
        this._listenMouseMove = false;
      }
    };
  }
}


// .................



<MyQuickPinchZoom
 ...
/>
```
