### ISSUE TITLE
Zoom start/end events not firing for wheel events

### ISSUE THREAD

**Issue by ashbrowning** [retyui/react-quick-pinch-zoom#3]
When I zoom on a MacBook trackpad (and therefore firing a wheel event), I'm able to get callbacks for `onZoomUpdate`, but nothing for `onZoomStart` and `onZoomEnd`. Can these be called to facilitate handling updates based on the zoom lifecycle when scrolling/using a trackpad?

Thanks for this package by the way - had fun playing around with it last night!

**Comment by retyui** [comment]
@ashbrowning Now I do not have time to correct this behavior. You can send your PR I will consider it

**Comment by retyui** [comment]
you can try alternative library: https://github.com/prc5/react-zoom-pan-pinch
