### ISSUE TITLE
Not able to swipe up or down on element inside QuickPinchZoom

### ISSUE THREAD

**Issue by bgakash93** [retyui/react-quick-pinch-zoom#33]
Hi, Just checking if element can detect touch events placed within QuickPinchZoom.

**Comment by retyui** [comment]
could you please create a demo ?
to show this issue

**Comment by lak-16** [comment]
I have similar issue. I have a vertically scrollable page with a video element in that page. I can scroll the page by touching anywhere on the page other than video element. If I remove QuickPinchZoom, I can touch video element and scroll the page

**Comment by retyui** [comment]
can you show what props do you spread to <video/> element?

**Comment by RisingGeek** [comment]
@bgakash93 You can use these props
```
 containerProps={{
     style: {
        touchAction: "auto",
     },
 }}
 draggableUnZoomed={false}
```
