### ISSUE TITLE
Module not found: Can't resolve 'classnames'

### ISSUE THREAD

**Issue by cnadolny2s** [retyui/react-quick-pinch-zoom#5]
```
Failed to compile.

./node_modules/react-quick-pinch-zoom/dist/index.es.js
Module not found: Can't resolve 'classnames' in '...\node_modules\react-quick-pinch-zoom\dist'
```

I'm using your main example and immediatelly getting this error. Any idea how to quick fix this at least temporary? Fork and add classnames dependency?

**Comment by retyui** [comment]
Classname is a peer dependency!

https://github.com/retyui/react-quick-pinch-zoom/blob/a2f78cc5c876f526fb94e730a30fea2d4ce4737b/package.json#L6-L8

So it is meant that you need install separately

```
yarn add classnames
```

**Comment by cnadolny2s** [comment]
Figured it out myself, but thanks for your quick response.
