### ISSUE TITLE
cancel handled touchEnd events

### ISSUE THREAD

**Issue by martinkutter** [retyui/react-quick-pinch-zoom#50]
Currently it is not possible to integrate this library to an application that handles for example swipe events on an outer element.
Imagine you want to use this library inside an image slider with touch support and the "wipe to next image" event is also triggered if you want to move your zoomed in image.

So it is necessary to cancel the touchEnd event, if it is handled by the library and let it bubble if not.

Cancel if:
* user performed a zoom interaction
* user performed a drag interaction if zoom factor is greather than 1

**Comment by martinkutter** [comment]
#51

**Comment by davydspotnana** [comment]
Note: It is possible to drag an image with `zoom factor = 1` when `verticalPadding` & `horizontalPadding` arent zero:

https://user-images.githubusercontent.com/95620376/165758316-4fbe4d10-7511-4363-85c9-20c634cffaf6.mp4


Could you please handle this case too?

**Comment by retyui** [comment]
- Released: [4.4.0](https://github.com/retyui/react-quick-pinch-zoom/blob/master/CHANGELOG.md#440)
- Diff: [4.3.0...4.4.0](https://npmfs.com/compare/react-quick-pinch-zoom/4.3.0/4.4.0/)
