### ISSUE TITLE
Tap events get accidentally canceled if `shouldCancelHandledTouchEndEvents` is enabled

### ISSUE THREAD

**Issue by martinkutter** [retyui/react-quick-pinch-zoom#52]
Accidentally a normal tap (click) on touch devices is also canceled if `shouldCancelHandledTouchEndEvents` is `true`.

**Comment by martinkutter** [comment]
fixed by #53

**Comment by retyui** [comment]
- Released: 4.4.1
- Diff: [4.4.0...4.4.1](https://npmfs.com/compare/react-quick-pinch-zoom/4.4.0/4.4.1/)
