### ISSUE TITLE
Feature request: two fingers pan only

### ISSUE THREAD

**Issue by 404-html** [retyui/react-quick-pinch-zoom#54]
It would be really nice to have an option to enable two-fingers pan only.
So single finger pan will do usual browser scrolling.

Just to achieve such effect:
https://developers.google.com/maps/documentation/embed/get-started

Perfect solution would be to allow mouse drag on desktop and two-fingers pan on touch.

**Comment by retyui** [comment]
That's an interesting approach. if you have ideas how to implement it PR welcome!

**Comment by retyui** [comment]
you can try alternative library: https://github.com/prc5/react-zoom-pan-pinch
