### ISSUE TITLE
Zooming on wheel without pressing any key

### ISSUE THREAD

**Issue by cojoclaudiu** [retyui/react-quick-pinch-zoom#59]
Hello, is there any posibility to zoom on wheel without pressing any key?

Thank you very much

**Comment by retyui** [comment]
yes

```tsx
const alwaysFalse = ()=> false;
//...

<QuickPinchZoom onUpdate={onUpdate} shouldInterceptWheel={alwaysFalse}>

```

docs: [`shouldInterceptWheel?: (WheelEvent) => boolean`](https://github.com/retyui/react-quick-pinch-zoom/blob/master/docs/api/README.md#shouldinterceptwheel-wheelevent--boolean)

**Comment by cojoclaudiu** [comment]
Amazing @retyui 
Thank you very much
