### ISSUE TITLE
Image Zoom Issue 

### ISSUE THREAD

**Issue by Anubhav234** [retyui/react-quick-pinch-zoom#63]
When clicking on the image for the very first time the transform scale is 1 and when clicking on the same image for the second time it is showing transform scale to be less than 1 .
first click 
![image](https://user-images.githubusercontent.com/65939999/204191335-112a6873-b399-43fa-bbc0-d29bd2ab873b.png)

second click of same image
![image](https://user-images.githubusercontent.com/65939999/204191499-48c15ced-73f7-4d32-87ea-bd2f1fc9ddcd.png)

**Comment by retyui** [comment]
how it possible? when I  click on img it's always zoom in 


https://user-images.githubusercontent.com/4661784/204269318-a15600ab-a93a-4016-8cea-5ee7a3254852.mp4
