### ISSUE TITLE
How to manually trigger zoom?

### ISSUE THREAD

**Issue by leandrocrs** [retyui/react-quick-pinch-zoom#66]
I need to trigger zoom by one click only. I'm able to capture the click and position X and Y related to the inner element where the user has clicked, and I'm using `quickRef.scaleTo({ scale: 2, x: innerEl.clientX, y: innerEl.clientY })` to make QuickPinch to the hard work.

However, the offset is wrong, and looking to the code I was not able to completely understand the logic to calculate proper X and Y positions.

I did also try to use `alignCenter`, but with no success either.

Any clue how can I achieve 1 click zoom?

Demo:
<video src="https://user-images.githubusercontent.com/1456009/218570958-a5ced0f4-0a1e-4e81-95d4-4ebf261ecf72.mp4"></video>

**Comment by retyui** [comment]
you can solve trying to find a combination for the next props:
```tsx
  tapZoomFactor={1}
  zoomOutFactor={1.3}
  maxZoom={5}
  minZoom={0.5}
```

**Comment by leandrocrs** [comment]
@retyui thanks for fast response!

My problem is to focus on point that user clicked. You can see in this video above that the zoom is applied next to click, but not in exact point. I'm passing clientX and clientY, but I'm not sure if I have to care about offset, and if so, what should I pass to make sure the exact point will be zoomed.

**Comment by leandrocrs** [comment]
For reference:

I did managed how to it. The mistake was not taking in account the [parent offset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent), so I have created a function to make the calculation:

```ts
const getZoomCoordinates = (ev: ReactMouseEvent<HTMLElement, MouseEvent>, innerEl: HTMLElement) => {
  const parentOffset = innerEl.offsetParent

  const parentClientRects = parentOffset?.getClientRects().item(0)

  return {
    x: ev.clientX - (parentClientRects?.left || 0),
    y: ev.clientY - (parentClientRects?.top || 0)
  }
}

// and when I call scaleTo, I call this helper function to give me the coordinates
const { x, y } = getZoomCoordinates(ev, innerRef.current)

quickPinchRef.current.scaleTo({
  x,
  y,
  scale,
  animated: true
})
```

Result:

<video src="https://user-images.githubusercontent.com/1456009/218784517-f5be7e3d-60c1-4d76-851e-b9d4cbe273e5.mov"></video>
