### ISSUE TITLE
use image resistance 

### ISSUE THREAD

**Issue by aminemohyeddine** [retyui/react-quick-pinch-zoom#68]
hello @retyui @bradcerasani @ashbrowning @nicolas-cusan @dminguez 
i really need help to complete the integration of your library in our app
i can't see this props in your documentation to use resistance : 
resistance={0.5}
background='white'

if not can i have a clue of how to do it with your library
thank you

**Comment by retyui** [comment]
we don't have a `resistance` prop


maybe this will help you:
```tsx
<QuickPinchZoom inertia={true} inertiaFriction={0.96} />

```

 Read docs: https://github.com/retyui/react-quick-pinch-zoom/blob/master/docs/api/README.md
