### ISSUE TITLE
Should tslib be a dependency?

### ISSUE THREAD

**Issue by tf** [retyui/react-quick-pinch-zoom#74]
I'm seeing Webpack dependency resolution errors that `tslib` is missing. I did not notice this during development since I had other packages that depended on `tslib` in my dev dependencies. During deploy it failed, though.

This library uses `importHelpers: true`, but declares `tslib` only as a `peerDependency`. Others (e.g., [1], [2]) seem to declare it as dependency as well. Alternatively, I think, it would need to be mentioned in the install instructions in the README.

Let me know what you think and I can create PR.

[1] https://github.com/dojo/meta/issues/226
[2] https://angular.io/guide/migration-update-libraries-tslib

**Comment by retyui** [comment]
Fixed in [`4.9.0`](https://github.com/retyui/react-quick-pinch-zoom/blob/master/CHANGELOG.md#490)

diff: [`4.8.0...4.9.0`](https://npmfs.com/compare/react-quick-pinch-zoom/4.8.0/4.8.0/)
