### ISSUE TITLE
When I build in a test environment NODE_ENV=test I have problem with require('prop-types')

### ISSUE THREAD

**Issue by epascal** [retyui/react-quick-pinch-zoom#76]
In line 1058 of component.tsx the test for production should be either test against production and test or for development

if (process.env.NODE_ENV !== 'production') { <--------------------------------  should be === 'development' or !== 'test! || !== 'production'
  const { any, element, object, number, func, bool } = require('prop-types');

  // @ts-ignore
  PinchZoom.propTypes = {
    children: element,
    containerProps: object,

if (process.env.NODE_ENV !== 'production') {

**Comment by epascal** [comment]
PS: really great component, thank you for the work

**Comment by retyui** [comment]
@epascal Why I have to exclude prop-types from test environment ? what problem do you have with `require('prop-types')`

**Comment by psalz** [comment]
I ran into this as well, the problem is that `prop-types` is not declared as a dependency of the package!

**Comment by retyui** [comment]
To fix it just install as dev deps. :

```tsx
yarn add -D prop-types
```
