### ISSUE TITLE
Need image to take up entire container

### ISSUE THREAD

**Issue by jonathanrstern** [retyui/react-quick-pinch-zoom#78]
Incredible library!

Is there a way to get the image to scale up (on initial load) so that it occupies the entire container?

**Comment by retyui** [comment]
can you show me an example how it should looks like ?

**Comment by fominv** [comment]
@jonathanrstern 

The `QuickPinchZoom` component has a `containerProps`. I used it to set Tailwind classes via `className`, but you could also probably use the `style` prop directly:

```jsx
<QuickPinchZoom onUpdate={onUpdate} containerProps={{ className: "fixed inset-0" }}>
  <img
    ref={imgRef}
    alt="Image for review"
    src={lastImage.url}
    className="w-full h-full object-cover"
  />
</QuickPinchZoom>
```

In your case, you could use `w-full h-full` instead of `fixed inset-0`.
