### ISSUE TITLE
Styling question

### ISSUE THREAD

**Issue by rurigrass** [retyui/react-quick-pinch-zoom#81]
Is there a way of styling the QuickPinchZoom container?

**Comment by retyui** [comment]
```tsx
<QuickPinchZoom 
  className={'your-class'}
  style={{
    // your style )
```

**Comment by rurigrass** [comment]
I get the following error:

 Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<PinchZoom> & Pick<Readonly<Props>, "onUpdate" | "children"> & InexactPartial<...> & InexactPartial<...>'.
  Overload 2 of 2, '(props: Props, context: any): PinchZoom', gave the following error.
    Type '{ children: Element; onUpdate: ({ x, y, scale }: { x: number; y: number; scale: number; }) => void; centerContained: true; doubleTapToggleZoom: true; wheelScaleFactor: number; shouldInterceptWheel: (event: WheelEvent) => boolean; style: {}; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<PinchZoom> & Pick<Readonly<Props>, "onUpdate" | "children"> & InexactPartial<...> & InexactPartial<...>'.
      Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<PinchZoom> & Pick<Readonly<Props>, "onUpdate" | "children"> & InexactPartial<...> & InexactPartial<...>'.ts(2769)

**Comment by retyui** [comment]
sorry my bad: 

that should works
```tsx
<QuickPinchZoom 
  containerProps={{
    className:className
    style: {/* your styles */},
  }}
```
