### ISSUE TITLE
react import missing in types.ts

### ISSUE THREAD

**Issue by shahshreya2108** [retyui/react-quick-pinch-zoom#85]
Getting below error while running `npm run build` in my project

`
(!) Plugin postcss: start value has mixed support, consider using flex-start instead src/Components/LineLinkDisplay/LineLinkItem/LineLinkItem.module.scss created dist/cjs, dist/es in 7.9s node_modules/react-quick-pinch-zoom/esm/PinchZoom/types.d.ts:28:21 - error TS2503: Cannot find namespace 'React'.  28     containerProps: React.HTMLAttributes<HTMLDivElement>;                        ~~~~~   Found 1 error in node_modules/react-quick-pinch-zoom/esm/PinchZoom/types.d.ts:28`

**Comment by retyui** [comment]
can you show stdout
```sh
npm list react @types/react
```

**Comment by shahshreya2108** [comment]
```
storefront-h5-sdk@3.0.10 /Users/shreyakotadia/Documents/Shreya/Workspace/paytm/storefront_h5_sdk
├─┬ react-dom@18.2.0
│ └── react@18.2.0 deduped
├─┬ react-quick-pinch-zoom@5.0.0
│ └── react@18.2.0 deduped
├─┬ react-visibility-sensor@5.1.1
│ └── react@18.2.0 deduped
└── react@18.2.0
```

**Comment by shahshreya2108** [comment]
Now getting below error:

```
node_modules/react-quick-pinch-zoom/esm/PinchZoom/component.d.ts:1:8 - error TS1259: Module '"/Users/shreyakotadia/Documents/Shreya/Workspace/test/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:32:1
    32 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/react-visibility-sensor/index.d.ts:34:38 - error TS2694: Namespace 'React' has no exported member 'StatelessComponent'.

34   const ReactVisibilitySensor: React.StatelessComponent<Props>;
                                        ~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  node_modules/react-quick-pinch-zoom/esm/PinchZoom/component.d.ts:1
     1  node_modules/react-visibility-sensor/index.d.ts:34
```

**Comment by retyui** [comment]
- fixed in [`5.1.0`](https://github.com/retyui/react-quick-pinch-zoom/releases/tag/5.1.0)
- npm diff [`5.0.0...5.1.0`](https://npmfs.com/compare/react-quick-pinch-zoom/5.0.0/5.1.0/)

**Comment by retyui** [comment]
thanks for letting me know)

**Comment by brightertools** [comment]
I seem to have this same error:
Could not resolve "prop-types"

Am following this example: https://blog.logrocket.com/adding-zoom-pan-pinch-react-web-apps/ 
but using vite

![image](https://github.com/retyui/react-quick-pinch-zoom/assets/6533238/fd2d15a6-813f-4aa3-ab4c-12808779b21f)

**Comment by retyui** [comment]
> I seem to have this same error: Could not resolve "prop-types"
> 
> Am following this example: https://blog.logrocket.com/adding-zoom-pan-pinch-react-web-apps/ but using vite
> 
> ![image](https://private-user-images.githubusercontent.com/6533238/295197673-fd2d15a6-813f-4aa3-ab4c-12808779b21f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzUxMzEsIm5iZiI6MTcwNDk3NDgzMSwicGF0aCI6Ii82NTMzMjM4LzI5NTE5NzY3My1mZDJkMTVhNi04MTNmLTRhYTMtYWI0Yy0xMjgwODc3OWIyMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMTIwNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE0NTVjMmZhNjc1OGJmYzQxYWYyZGQwMGJiOWYyMzNjOTEyMjgyOWFiZjA2ZDgyMThlMGJiZThkOGU1MTQwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mxJmaz8Kb_nH0FUL7LjUmIHAi8K14xVhRF1a1DJC5B0)
> 
> +-- @types/react-dom@18.2.18 | `-- @types/react@18.2.47 deduped +-- @types/react@18.2.47 +-- react-dom@18.2.0 | `-- react@18.2.0 deduped +-- react-quick-pinch-zoom@5.1.0 | `-- react@18.2.0 deduped `-- react@18.2.0

see: https://github.com/retyui/react-quick-pinch-zoom/issues/76#issuecomment-1668561252
