### ISSUE TITLE
[README] Link to web demos is not working

### ISSUE THREAD

**Issue by a-fortunato** [retyui/react-quick-pinch-zoom#88]
Hi!

On the [Links](https://github.com/retyui/react-quick-pinch-zoom?tab=readme-ov-file#links) section of the README, the [Web demos](https://react-quick-pinch-zoom.netlify.com/) link is returning a `404`.

<img width="1048" alt="Screenshot 2024-05-20 at 14 23 03" src="https://github.com/retyui/react-quick-pinch-zoom/assets/6339463/75e9cf3f-baa4-4b2a-bca8-b45ad91b05ab">

**Comment by retyui** [comment]
thx
fixed: https://github.com/retyui/react-quick-pinch-zoom/commit/0731003aefb7744df2f649054714b588fb96d0c4
