### ISSUE TITLE
Disable CTRL-Key on mouswheel

### ISSUE THREAD

**Issue by daniel6691** [retyui/react-quick-pinch-zoom#90]
Add a parameter to disable the mandatory use of the ctrl-key please

**Comment by retyui** [comment]
I think this prop should help:
https://github.com/retyui/react-quick-pinch-zoom/blob/master/docs/api/README.md#shouldinterceptwheel-wheelevent--boolean

**Comment by daniel6691** [comment]
thx, i've already implemented it for myself - just thought an official option would be nice
